### ISSUE TITLE
what should i do if i need do something before the activity's onDestroy()

### ISSUE THREAD

**Issue by Liaox** [eyeem/decorator#22]
now ,the DecoratedActivity is like this:
```Java
@Override
   protected void onDestroy() {
      super.onDestroy();
      decorators.onDestroy();
   }
```
all decorators.onDestroy() is run after super.onDestroy();
but,i want do something before super.onDestroy().what should i do?
thanks!

**Comment by ronaldoeyeem** [comment]
you always have to create your own `MyClass extends DecoratedClass`; so to change the order you can do on that class. For example:
```Java
// on your MyClass extends DecoratedClass

@Override
protected void onDestroy() {
   // add code here to be executed before decorators
   super.onDestroy();   // decorators.onDestroy() is being called inside this super
   // add code here to be executed after decorators
}
```

**Comment by ronaldoeyeem** [comment]
@Liaox 
directly changing changing the order of execution is currently not possible, maybe we could do with some extra annotation on the method, something like `@beforeSuper`.

another option to my previous comment (that we did on our app) is to create a callback specifically for that. For example

```Java
// on your Blueprint
public void beforeOnDestroy(){}
```

then on your `MyClass extends DecoratedClass`
```Java
@Override
protected void onDestroy() {
   beforeOnDestroy(); // this gets called for all decoratos
   super.onDestroy();   // decorators.onDestroy() is being called inside this super (if you define `onDestroy` on the blueprint
   unbind(); // always unbind, inside this method your decorators will lose reference to the decoratedClass.
}
```

**Comment by Liaox** [comment]
thanks!

**Comment by ronaldoeyeem** [comment]
there @Liaox 
I created a ticket for this specific enhancement, if you want to track https://github.com/eyeem/decorator/issues/24.
I'm not sure when we'll have time for it, but at least we don't forget.
