### ISSUE TITLE
is this support fragmentblueprint and activityblueprint share the decorator

### ISSUE THREAD

**Issue by Liaox** [eyeem/decorator#25]
like that，could i use the "RequestInstigator.java" in the activity or fragment without write two java file？
in fragment:
```Java
@Decorate(decorator = "FDeco",
    decoratored="DecoFragment"
)
public class FragmentBluePrint extends Fragment{...}
```
in activity:
```Java
@Decorate(decorator = "Deco",decoratored = "DecoActivity")
public class ActivityBluePrint extends AppCompatActivity {...}
```
if i change the "FDeco" to "Deco" ,build failed.so i must write two file,one extends FDeco ,one extends Deco? even only the extends is different.
can you give me any suggestion on this matter?
Please forgive my poor English.thanks!

**Comment by ronaldoeyeem** [comment]
Hi @Liaox 

The generated code is totally isolated from each other and there's real way to couple them together.
The `DecoFragment.Builder` will expect a `class` that extends `FDeco` and the `DecoActivity.Builder` will expect a `class` that extends `Deco`.

BUT, using the normal Android interaction between Activity and Fragment, should be easy enough to share a `RequestInstigator`. Something like this.

in a fragment decorator
```Java
public class Foo extends FDeco {
    public void someMethod(){
        DecoActivity act = (DecoActivity)getDecorated().getActivity();
        act.getDecorators().... call here any method from the AppCompatActivityDecorators
        Deco.InstigateActSomething activityDecorator = act.getDecorators().getFirstDecoratorOfType(Deco.InstigateActSomething.class);
    }
}
```

in an activity decorator
```Java
public class Bar extends Deco {
   public void someMethod(){
        FDeco fDeco = getDecorated().getSupportFragmentManager().findFragmentById(R.id.frag);
        fDeco.getDecorators()... call here any method from the FragmentDecorators
        Deco.InstigateFragSomething activityDecorator = fDeco.getDecorators().getFirstDecoratorOfType(FDeco.InstigateFragSomething.class);
   }
}
```

if that answers your question, please close the issue.

**Comment by Liaox** [comment]
thanks!
